name: dio_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# flutter version
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# add dependencies
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.6
  get: ^4.6.6
  dio: ^5.4.0
  permission_handler: ^11.2.0
  device_info_plus: ^9.1.2
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  cloud_firestore: ^4.15.4
#  percent_indicator: ^4.0.1
  graphql_flutter: ^5.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  firebase_database: ^10.4.7
#  video_compress: ^3.1.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter

# flutter lints dependencies
#  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  # add different assets
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # add different fonts
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
